if (WIN32)
  include(cmake/windows/FindGLFW.cmake)
  include(cmake/windows/FindSpdlog.cmake)
  include(cmake/windows/FindVulkan.cmake)
  include(cmake/windows/FindTomlpp.cmake)
elseif(UNIX)
  include(cmake/unix/FindGLFW.cmake)
  include(cmake/unix/FindSpdlog.cmake)
  include(cmake/unix/FindVulkan.cmake)
endif()
